<?php

namespace Site\HomeBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * Commonrepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Homerepository extends DocumentRepository
{
}