<?php

namespace Site\HomeBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * Navigaterepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Navigaterepository extends DocumentRepository
{
	public function findAllByOrder()
    {
        return $this->createQueryBuilder()
            ->sort('order', 'ASC')
            ->getQuery()
            ->execute();
    }
}