<?php

namespace Site\LessonBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * LevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LevelRepository extends DocumentRepository
{
	public function findAllByOrder()
	{
		return $this->createQueryBuilder()
		       ->sort('order', 'ASC')
               ->getQuery()
               ->execute();
	}
}