<?php

namespace Site\CommonBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * Commonrepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Commonrepository extends DocumentRepository
{
}